import {
  faTachometerAlt,
  faExchangeAlt,
  faWallet,
  faStore,
  faChartLine,
  faDollarSign,
  faBuilding,
  faChartBar,
  faMapMarkedAlt,
  faHome,
  faUsers,
  faWalking,
  faBriefcase,
} from "@fortawesome/free-solid-svg-icons";
import "./customScrollbar.css";

export const quickAccessItems = [
  { name: "Dashboard", icon: faTachometerAlt, id: "dashboard" },
  { name: "Exchange", icon: faExchangeAlt, id: "exchange" },
  { name: "My Wallet", icon: faWallet, id: "my_wallet" },
  { name: "Tradeview", icon: faChartLine, id: "tradeview" },
];

export const menuItems = [
  {
    name: "점포 정보",
    id: "store_info",
    icon: faStore,
    options: [
      { name: "점포 수", category: "기타" },
      { name: "개업 점포 수", category: "기타" },
      { name: "폐업 점포 수", category: "기타" },
      { name: "프렌차이즈 점포 수", category: "기타" },
      { name: "유사 업종 점포 수", category: "기타" },
      { name: "개업율", category: "기타" },
      { name: "폐업율", category: "기타" },
    ],
  },
  {
    name: "변화 지표",
    id: "change_indicators",
    icon: faChartLine,
    options: [
      { name: "영업 개월 평균 (서울)", category: "기타" },
      { name: "영업 개월 평균", category: "기타" },
      { name: "상권 변화 지표명", category: "기타" },
      { name: "폐업 영업 개월 평균(서울)", category: "기타" },
      { name: "폐업 영업 개월 평균", category: "기타" },
    ],
  },
  {
    name: "비용",
    id: "cost",
    icon: faDollarSign,
    options: [
      { name: "여가 지출", category: "기타" },
      { name: "유흥 지출", category: "기타" },
      { name: "의료비 지출", category: "기타" },
      { name: "교육 지출", category: "기타" },
      { name: "문화 지출", category: "기타" },
      { name: "지출 총금액", category: "기타" },
      { name: "식료품 지출", category: "기타" },
      { name: "의류 신발 지출", category: "기타" },
      { name: "생활 용품 지출", category: "기타" },
      { name: "교통 지출", category: "기타" },
      { name: "소득 구간", category: "기타" },
      { name: "월 평균 소득", category: "기타" },
    ],
  },
  {
    name: "시설",
    id: "facility",
    icon: faBuilding,
    options: [
      { name: "유치원", category: "기타" },
      { name: "버스 정거장", category: "기타" },
      { name: "철도 역", category: "기타" },
      { name: "백화점", category: "기타" },
      { name: "슈퍼마켓", category: "기타" },
      { name: "고등학교", category: "기타" },
      { name: "대학교", category: "기타" },
      { name: "종합병원", category: "기타" },
      { name: "초등학교", category: "기타" },
      { name: "관공서", category: "기타" },
      { name: "은행", category: "기타" },
      { name: "극장", category: "기타" },
      { name: "공항", category: "기타" },
      { name: "버스 터미널", category: "기타" },
      { name: "집객시설", category: "기타" },
      { name: "숙박시설", category: "기타" },
      { name: "중학교", category: "기타" },
      { name: "약국", category: "기타" },
      { name: "일반 병원", category: "기타" },
      { name: "지하철 역", category: "기타" },
    ],
  },
  {
    name: "매출",
    id: "sales",
    icon: faChartBar,
    options: [
      { name: "10대 금액", category: "연령대" },
      { name: "10대 건수", category: "연령대" },
      { name: "20대 금액", category: "연령대" },
      { name: "20대 건수", category: "연령대" },
      { name: "30대 금액", category: "연령대" },
      { name: "30대 건수", category: "연령대" },
      { name: "40대 금액", category: "연령대" },
      { name: "40대 건수", category: "연령대" },
      { name: "50대 금액", category: "연령대" },
      { name: "50대 건수", category: "연령대" },
      { name: "60대이상 금액", category: "연령대" },
      { name: "60대이상 건수", category: "연령대" },
      { name: "0~6시 금액", category: "시간대" },
      { name: "0~6시 건수", category: "시간대" },
      { name: "6~11시 금액", category: "시간대" },
      { name: "6~11시 건수", category: "시간대" },
      { name: "11~14시 금액", category: "시간대" },
      { name: "11~14시 건수", category: "시간대" },
      { name: "14~17시 금액", category: "시간대" },
      { name: "14~17시 건수", category: "시간대" },
      { name: "17~21시 금액", category: "시간대" },
      { name: "17~21시 건수", category: "시간대" },
      { name: "21~24시 금액", category: "시간대" },
      { name: "21~24시 건수", category: "시간대" },
      { name: "월요일 금액", category: "요일" },
      { name: "월요일 건수", category: "요일" },
      { name: "화요일 금액", category: "요일" },
      { name: "화요일 건수", category: "요일" },
      { name: "수요일 금액", category: "요일" },
      { name: "수요일 건수", category: "요일" },
      { name: "목요일 금액", category: "요일" },
      { name: "목요일 건수", category: "요일" },
      { name: "금요일 금액", category: "요일" },
      { name: "금요일 건수", category: "요일" },
      { name: "토요일 금액", category: "요일" },
      { name: "토요일 건수", category: "요일" },
      { name: "일요일 금액", category: "요일" },
      { name: "일요일 건수", category: "요일" },
      { name: "남성 금액", category: "성별" },
      { name: "남성 건수", category: "성별" },
      { name: "여성 금액", category: "성별" },
      { name: "여성 건수", category: "성별" },
      { name: "주중 금액", category: "기간" },
      { name: "주중 건수", category: "기간" },
      { name: "주말 금액", category: "기간" },
      { name: "주말 건수", category: "기간" },
      { name: "당월 금액", category: "기간" },
      { name: "당월 건수", category: "기간" },
    ],
  },
  {
    name: "지역",
    id: "region",
    icon: faMapMarkedAlt,
    options: [
      { name: "자치구", category: "기타" },
      { name: "행정동", category: "기타" },
      { name: "영역 면적", category: "기타" },
    ],
  },
  {
    name: "아파트",
    id: "apartment",
    icon: faHome,
    options: [
      { name: "아파트 단지 수", category: "기타" },
      { name: "아파트 평균 면적", category: "기타" },
      { name: "아파트 평균 시가", category: "기타" },
      { name: "아파트 1억미만 세대 수", category: "기타" },
      { name: "아파트 1억 세대 수", category: "기타" },
      { name: "아파트 2억 세대 수", category: "기타" },
      { name: "아파트 3억 세대 수", category: "기타" },
      { name: "아파트 4억 세대 수", category: "기타" },
      { name: "아파트 5억 세대 수", category: "기타" },
      { name: "아파트 6억이상 세대 수", category: "기타" },
      { name: "아파트 66제곱미터 미만 세대 수", category: "기타" },
      { name: "아파트 66제곱미터 세대 수", category: "기타" },
      { name: "아파트 99제곱미터 세대 수", category: "기타" },
      { name: "아파트 132제곱미터 세대 수", category: "기타" },
      { name: "아파트 165제곱미터 세대 수", category: "기타" },
    ],
  },
  {
    name: "인구",
    id: "population",
    icon: faUsers,
    options: [
      { name: "총 인구 수", category: "기타" },
      { name: "10대 남성 인구 수", category: "연령대" },
      { name: "20대 남성 인구 수", category: "연령대" },
      { name: "30대 남성 인구 수", category: "연령대" },
      { name: "40대 남성 인구 수", category: "연령대" },
      { name: "50대 남성 인구 수", category: "연령대" },
      { name: "60대 이상 남성 인구 수", category: "연령대" },
      { name: "10대 여성 인구 수", category: "연령대" },
      { name: "20대 여성 인구 수", category: "연령대" },
      { name: "30대 여성 인구 수", category: "연령대" },
      { name: "40대 여성 인구 수", category: "연령대" },
      { name: "50대 여성 인구 수", category: "연령대" },
      { name: "60대 이상 여성 인구 수", category: "연령대" },
      { name: "10대 인구 수", category: "연령대" },
      { name: "20대 인구 수", category: "연령대" },
      { name: "30대 인구 수", category: "연령대" },
      { name: "40대 인구 수", category: "연령대" },
      { name: "50대 인구 수", category: "연령대" },
      { name: "60대 여성 인구 수", category: "연령대" },
      { name: "남성 인구 수", category: "성별" },
      { name: "여성 인구 수", category: "성별" },
      { name: "아파트 가구 수", category: "기타" },
      { name: "비 아파트 가구 수", category: "기타" },
      { name: "총 가구 수", category: "기타" },
    ],
  },
  {
    name: "유동 인구",
    id: "floating_population",
    icon: faWalking,
    options: [
      { name: "남성 유동 인구 수", category: "성별" },
      { name: "여성 유동 인구 수", category: "성별" },
      { name: "일요일 유동 인구 수", category: "요일" },
      { name: "월요일 유동 인구 수", category: "요일" },
      { name: "화요일 유동 인구 수", category: "요일" },
      { name: "수요일 유동 인구 수", category: "요일" },
      { name: "목요일 유동 인구 수", category: "요일" },
      { name: "금요일 유동 인구 수", category: "요일" },
      { name: "토요일 유동 인구 수", category: "요일" },
      { name: "10대 유동인구 수", category: "연령대" },
      { name: "20대 유동인구 수", category: "연령대" },
      { name: "30대 유동인구 수", category: "연령대" },
      { name: "40대 유동인구 수", category: "연령대" },
      { name: "50대 유동인구 수", category: "연령대" },
      { name: "60대이상 유동인구 수", category: "연령대" },
      { name: "0~6시 유동인구 수", category: "시간대" },
      { name: "6~11시 유동인구 수", category: "시간대" },
      { name: "11~14시 유동인구 수", category: "시간대" },
      { name: "14~17시 유동인구 수", category: "시간대" },
      { name: "17~21시 유동인구 수", category: "시간대" },
      { name: "21~24시 유동인구 수", category: "시간대" },
    ],
  },
  {
    name: "직장",
    id: "work_population",
    icon: faBriefcase,
    options: [
      { name: "총 직장인구 수", category: "기타" },
      { name: "남성 10대 직장인구 수", category: "연령대" },
      { name: "남성 20대 직장인구 수", category: "연령대" },
      { name: "남성 30대 직장인구 수", category: "연령대" },
      { name: "남성 40대 직장인구 수", category: "연령대" },
      { name: "남성 50대 직장인구 수", category: "연령대" },
      { name: "남성 60대이상 직장인구 수", category: "연령대" },
      { name: "여성 10대 직장인구 수", category: "연령대" },
      { name: "여성 20대 직장인구 수", category: "연령대" },
      { name: "여성 30대 직장인구 수", category: "연령대" },
      { name: "여성 40대 직장인구 수", category: "연령대" },
      { name: "여성 50대 직장인구 수", category: "연령대" },
      { name: "여성 60대이상 직장인구 수", category: "연령대" },
      { name: "10대 직장인구 수", category: "연령대" },
      { name: "20대 직장인구 수", category: "연령대" },
      { name: "30대 직장인구 수", category: "연령대" },
      { name: "40대 직장인구 수", category: "연령대" },
      { name: "50대 직장인구 수", category: "연령대" },
      { name: "60대이상 직장인구 수", category: "연령대" },
      { name: "남성 직장인구 수", category: "성별" },
      { name: "여성 직장인구 수", category: "성별" },
    ],
  },
];
